增加 dotnet 实现的一个 GitHub proxy
WeNeedHome/SummaryOfLoanSuspension pull request #953
Opened 2022-07-20 17:07 UTC by WeihanLi

演示地址：<https://weneedhome.weihanli.xyz>

2022-07-20 18:07 UTC, zhhrz commented
SSL 证书不可信？重新签发一下

2022-07-20 19:56 UTC, zhhrz commented
奥，换了台设备是好的。可能是我一个电脑上根证书的问题

2022-07-21 02:32 UTC, MarkShawn2020 requested changes
good job
方便把这个实现更新在首页readme的开发记录里吗？

2022-07-21 06:40 UTC, merged

2022-07-21 10:24 UTC, WeihanLi commented
> 方便把这个实现更新在首页readme的开发记录里吗？

抱歉，白天在忙，没时间弄，谢谢

2022-07-21 11:41 UTC, MarkShawn2020 commented
> > 方便把这个实现更新在首页readme的开发记录里吗？
> 
> 抱歉，白天在忙，没时间弄，谢谢

没事，我已经帮你更新了